# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginregistration', '0002_auto_20170124_0351'),
        ('courses', '0003_auto_20170124_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='loginregistration.User')),
            ],
            managers=[
                ('user_course_Mgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
